repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.38.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: migrations

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.138
    hooks:
      - id: ruff

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: "mypy"
        exclude: "(migrations|oauth_backends.py)/"
